### ISSUE TITLE
Define Milestones & Plan

### ISSUE THREAD

**Issue by omerakben** [nss-evening-cohort-29/OLJ-Gitsub#44]
Step 1: Analyze the Project Requirements  

- [x] Create an Overview page milestone
- [x] Create a Repos page milestone
- [x] Create a Project page milestone
- [x] Create a Packages page milestone

Step 2: Decide a structure architect
- [x] Create an HTML structure plan
- [x] Create a JS strucre plan
- [x] Create a design CSS , Boostrap plan
